`use strict`;

const FILE_NAME = `./mocks.json`;

const POSTS_MIN_AMOUNT = 1;

const POSTS_MAX_AMOUNT = 1000;

const CREATE_DATE_MAX_UNIX_TIME_STAMP = Date.now();

const ONE_MONTH_UNIX_TIME_STAMP = 2670658033;

const CREATE_DATE_MIN_UNIX_TIME_STAMP = CREATE_DATE_MAX_UNIX_TIME_STAMP - ONE_MONTH_UNIX_TIME_STAMP * 3;

const TEXT_SENTENCES_MAX_AMOUNT = 5;

const CATEGORIES_MAX_AMOUNT = 3;

const SENTENCES_FILE_PATH = `./data/sentences.txt`;

const CATEGORIES_FILE_PATH = `./data/categories.txt`;

const TITLES_FILE_PATH = `./data/titles.txt`;

module.exports = {
  FILE_NAME,
  POSTS_MIN_AMOUNT,
  POSTS_MAX_AMOUNT,
  CREATE_DATE_MAX_UNIX_TIME_STAMP,
  CREATE_DATE_MIN_UNIX_TIME_STAMP,
  TEXT_SENTENCES_MAX_AMOUNT,
  CATEGORIES_MAX_AMOUNT,
  SENTENCES_FILE_PATH,
  CATEGORIES_FILE_PATH,
  TITLES_FILE_PATH,
};
