parser: 'babel-eslint'

parserOptions:
  ecmaVersion: 2018

env:
  es6: true
  node: true

plugins:
  - babel
  - jsdoc

rules:
  no-invalid-this: 0
  babel/no-invalid-this: 1

extends:
  - htmlacademy/node

settings:
  jsdoc:
    tagNamePreference:
      returns: return
