'use strict';

const PageId = {
  ERROR: `ERROR`,
  MAIN: `MAIN`,
  SEARCH: `SEARCH`,
  SIGN_IN: `SIGN_IN`,
  SIGN_UP: `SIGN_UP`,
  POST: `POST`,
  POSTS_BY_CATEGORY: `POSTS_BY_CATEGORY`,
  ADMIN_CATEGORIES: `ADMIN_CATEGORIES`,
  ADMIN_COMMENTS: `ADMIN_COMMENTS`,
  ADMIN_NEW_POST: `ADMIN_NEW_POST`,
  ADMIN_EDIT_POST: `ADMIN_EDIT_POST`,
  ADMIN_POSTS: `ADMIN_POSTS`,
};

module.exports = {PageId};
